TApplicationException: Move to top-level internal package
This moves TApplicationException to the top-level internal package so that
it's accessible from more thriftrw packages. Specifically, this is needed for
the plugin system because we use Thrift envelopes to talk to the plugins.